version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    container_name: subscriber_db
    environment:
      - MYSQL_ROOT_PASSWORD="root"
      - MYSQL_USER="root"
      - MYSQL_DATABASE="logs"
    ports:
      - "10001:3306"
    volumes:
      - ./data:/var/lib/mysql